/*
 * usart_user.c
 *
 *  Created on: Mar 10, 2026
 *      Author: oscar
 */

#include "usart_user.h"

void usart2_init(void) {
	// enable clock
	RCC->APB1ENR |= RCC_APB1ENR_USART2EN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	RCC->AHB1ENR |= RCC_AHB1ENR_DMA1EN;

	// GPIO PA2
	GPIOA->MODER &= ~GPIO_MODER_MODER2_0;
	GPIOA->MODER |= GPIO_MODER_MODER2_1;

	GPIOA->OTYPER &= ~ GPIO_OTYPER_OT2;

	GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR2_0;
	GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR2_1;

	GPIOA->PUPDR &= ~GPIO_PUPDR_PUPDR2_0;
	GPIOA->PUPDR &= ~GPIO_PUPDR_PUPDR2_1;

	GPIOA->AFR[0] |= GPIO_AFRL_AFRL2_0;
	GPIOA->AFR[0] |= GPIO_AFRL_AFRL2_1;
	GPIOA->AFR[0] |= GPIO_AFRL_AFRL2_2;
	GPIOA->AFR[0] &= ~GPIO_AFRL_AFRL2_3;

	// Basic Parameters
	USART2->CR1 &= ~USART_CR1_UE;

	USART2->BRR = 0x1B2; // 115200 baud @ 50 MHz

	USART2->CR1 |= USART_CR1_TE;
	USART2->CR1 |= USART_CR1_RE;

	USART2->CR3 |= USART_CR3_HDSEL;
	USART2->CR3 |= USART_CR3_DMAT;
	USART2->CR3 |= USART_CR3_DMAR;

	USART2->CR1 |= USART_CR1_UE;
}
